{"Austria": {"Bundesliga": ["Admira Vienna",
                                    "Austria Wien",
                                    "LASK",
                                    "Rapid Wien",
                                    "RB Salzburg",
                                    "Rhiendorf Altach",
                                    "St. Polten",
                                    "Sturm Graz",
                                    "SV Ried",
                                    "TSV Hartburg",
                                    "Wolfsberger AC",
                                    "WSG Tirol"]},
         "Azerbaijan": {"Premiere League": ["Gabala",
                                            "Kesla",
                                            "Neftchi Baku",
                                            "Qarabag",
                                            "Sabah",
                                            "Sumgayit",
                                            "Zira"]},
         "Belgium": {"Pro League": ["Anderlecht",
                                    "Antwerp",
                                    "Beerschot",
                                    "Cercle Brugge",
                                    "Charleroi",
                                    "Club Brugge",
                                    "Eupen",
                                    "Genk",
                                    "Gent",
                                    "Kortrijk",
                                    "Mechelen",
                                    "Oostende",
                                    "Oud-Heverlee Leuven",
                                    "Sint-Truiden",
                                    "Standard Liege",
                                    "Waasland Beveren",
                                    "Zuite Waregem"]},
         "Czech Republic": {"Czech First League": ["Banik Ostrava",
                                                   "Bohemians 1905",
                                                   "Ceske Budejovice",
                                                   "Fastav Zlin",
                                                   "FK Pardubice",
                                                   "Jablonec",
                                                   "Karvina",
                                                   "Mlada Boleslav",
                                                   "Opava",
                                                   "Pribram",
                                                   "Sigma Olomuc",
                                                   "Slavia Prague",
                                                   "Slovacko",
                                                   "Slovan Liberec",
                                                   "Sparta Prague",
                                                   "Teplice",
                                                   "Victoria Plzen",
                                                   "Zbrojovka Brno"]},
         "England": {"Premiere League": ["Arsenal",
                                          "Chelsea"],
                      "Championship": ["Watford",
                                       "Norwich City"],
                      "League 1": ["Some Club",
                                   "Other FC"],
                      "League 2": ["Tiny Club",
                                   "Accrington Stanley"]}


         }